<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Assistant.Interfaces\Assistant.Interfaces.csproj" />
    <ProjectReference Include="..\Assistant.Contracts\Assistant.Contracts.csproj" />
    <ProjectReference Include="..\Assistant.Models\Assistant.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="Telegram.Bot" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
