// <auto-generated />
using System;
using Assistant.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assistant.Repository.Migrations
{
    [DbContext(typeof(AssistantDbContext))]
    [Migration("20260822202918_AddDueReminderIndex")]
    partial class AddDueReminderIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assistant.Models.ReminderTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset?>("ReminderSentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reminder_sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("idx_tasks_due_pending")
                        .HasFilter("status = 1 AND reminder_sent_at IS NULL");

                    b.ToTable("reminder_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_tasks_sent_requires_due", "reminder_sent_at IS NULL OR due_at IS NOT NULL");

                            t.HasCheckConstraint("ck_reminder_tasks_status_known", "status <> 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
