<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Assistant.Worker-d599c905-7a11-40dd-93c9-f4e7515b8d8d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Assistant.Repository\Assistant.Repository.csproj" />
    <ProjectReference Include="..\Assistant.Impl\Assistant.Impl.csproj" />
    <ProjectReference Include="..\Assistant.Interfaces\Assistant.Interfaces.csproj" />
    <ProjectReference Include="..\Assistant.Contracts\Assistant.Contracts.csproj" />
    <ProjectReference Include="..\Assistant.Models\Assistant.Models.csproj" />
  </ItemGroup>
</Project>
